{
  imports = [
    ./dunst.nix
    ./flameshot.nix
    ./fuzzel.nix
    ./hyprlock.nix
    ./i18n.nix
    ./kitty.nix
    ./libskk
    ./niri
    ./obs-studio.nix
    ./onlyoffice.nix
    ./wallpaper_random.nix
    ./waybar.nix
    ./wleave.nix
    ./xremap.nix
    ./zen-browser.nix
  ];
}
